name: Linux

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-16.04
        cuda:
        - "10.2"
        include:
        - os: ubuntu-16.04
          cuda: "9.2"

    steps:
    - uses: actions/checkout@v2

    - name: Install CUDA
      env:
        CUDA: ${{ matrix.cuda }}
      run: .github/tools/linux-install-cuda.sh

    - name: cmake
      run: cmake . -DSPACEMESHVULKAN=OFF

    - name: make
      run: make .

    - uses: actions/upload-artifact@v2
      with:
        name: library
        path: src/libgpu-setup.so
